version: '3'
services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8000:80"
    env_file:
      - gateway/.env
    depends_on:
      - statistic
      - db_gateway
  statistic:
    build:
      context: .
      dockerfile: statistic/Dockerfile
    ports:
      - "50051:50051"
    env_file:
      - statistic/.env
    depends_on:
     - db_statistics

  db_gateway:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  db_statistics:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
